### PR TITLE
fix: check for installer image before proceeding with upgrade

### LINKED ISSUE #1606: Fail fast on upgrade if image is unavailable
Currently we get pretty far into an upgrade before we attempt to pull the upgrade container. With the need to specify the image with `docker.io` or 'registry', this can inadvertently break a node. 
We should attempt to pull the image / verify the image prior to initiating the upgrade.

### PR DESCRIPTION
**Pull request by rsmitty**
This PR will add in some code to pre-pull the installer image before we
run an upgrade of a given talos node. Additionally, this will add some
functional args to the install package to allow for specifying whether
or not to pull the installer image. This was needed since there was no
sense in pulling the installer again once we made it that far into the
upgrade process.

Will close #1606 

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

### CODE REVIEW

File: internal/pkg/install/options.go [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+package install
+
+// Option controls generate options specific to input generation.
+type Option func(o *Options) error
+
+// WithExistingImage specifies whether to pull the installer image during an install
+func WithExistingImage() Option {
```
Comment (andrewrynhard) [inline internal/pkg/install/options.go]: nit: Should we make this `WithPullImage` if we want to use `PullImage` as the field? If we want `WithExistingImage`, maybe we should make the field `ExistingImage` or something like that. At the end of the day, I don't care either way, but I feel like there is some double negation type thinking this forces me to do since `WithExistingImage` sort of inverts what the field `PullImage` makes you think. Can you tell I'm confused? :D

File: internal/pkg/install/install.go [hunk 2]
```diff
@@ -21,17 +21,34 @@ import (
...
-		return err
+	var image containerd.Image
+
+	if options.PullImage {
+		image, err = client.Pull(ctx, r.Config().Machine().Install().Image(), []containerd.RemoteOpt{containerd.WithPullUnpack}...)
+		if err != nil {
+			return err
+		}
+	} else {
+		image, err = client.GetImage(ctx, r.Config().Machine().Install().Image())
```
Comment (andrewrynhard) [inline internal/pkg/install/install.go]: Good idea. Brings some assurance that the image exists.

File: internal/app/machined/internal/api/reg/reg.go [hunk 3]
```diff
@@ -97,7 +98,18 @@ func (r *Registrator) Shutdown(ctx context.Context, in *empty.Empty) (reply *mac
 
 // Upgrade initiates an upgrade.
 func (r *Registrator) Upgrade(ctx context.Context, in *machineapi.UpgradeRequest) (data *machineapi.UpgradeResponse, err error) {
-	if err = etcd.ValidateForUpgrade(); err != nil {
```
Comment (andrewrynhard) [inline internal/app/machined/internal/api/reg/reg.go]: I think this should still be here.

Comment (rsmitty) [reply internal/app/machined/internal/api/reg/reg.go]: yep, thx.
