### PR TITLE
fix: respect nameservers when using docker cluster

### LINKED ISSUE #2109: "talos cluster --nameserver $nameservers" is ignored by talos container
### Description

Hi, first of: I love your project & i wanted to give talos a shot in my dev environment. Sadly I ran into a problem, setting the Nameservers. As it seems `talosctl` is parsing the IPs just fine, but the running talos containers do not use these nameservers.

This causes the problem that - since my firewall doesn't allow clear DNS into the internet - the `k8s.gcr.io/etcd:3.3.15-0` image can not be pulled. 

I tested it on two different machines, both running up2date Debian buster. Maybe it's what you mean by `(VM only)` in `--nameservers strings         list of nameservers to use (VM only) (default [8.8.8.8,1.1.1.1]) `. Anyways, this seems pretty bad for airgapped systems.

I've set the dns-servers in my docker daemon.json, too:
``` json
 # cat /etc/docker/daemon.json 
{
  "dns": ["192.168.1.111", "192.168.1.1"]
}
```

cmdline: `talosctl cluster create --wait --nameservers "192.168.1.111,192.168.1.1"`

"Proof":
```
 # docker cp ${master-id}:/etc/resolv.conf .
 # cat resolv.conf 
nameserver 1.1.1.1
nameserver 8.8.8.8
```
### Logs

From master / talosctl output:
``` 
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": 6 error(s) occurred:
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:34080->8.8.8.8:53: i/o timeout
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:39899->8.8.8.8:53: read: connection refused
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:37123->8.8.8.8:53: read: connection refused
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:58186->8.8.8.8:53: i/o timeout
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:58074->8.8.8.8:53: i/o timeout
        timeout
context deadline exceeded
```

### Environment

- Talos version: 0.4.1 & 0.5.0-beta.0
- Kubernetes version: v1.17.0
- Platform: debian:buster / amd64

### PR DESCRIPTION
**Pull request by rsmitty**
This PR will fix some unexpected user behavior where nameservers were
always getting written to 8.8.8.8,1.1.1.1 for the docker-based talos
clusters. This occurred even when updating the docker daemon's config.
This PR will make the docker provisioner respect the --nameserver flag
and allow that to be used to override the defaults.

Should close #2109.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2112)

### CODE REVIEW

File: internal/pkg/provision/providers/docker/docker.go [hunk 1]
```diff
@@ -43,9 +44,24 @@ func (p *provisioner) Close() error {
...
 		generate.WithPersist(false),
 	}
+
+	if len(networkReq.Nameservers) > 0 {
+		nameservers := make([]string, len(networkReq.Nameservers))
+		for i := range nameservers {
+			nameservers[i] = networkReq.Nameservers[i].String()
+		}
+
+		ret = append(ret, generate.WithNetworkConfig(
```
Comment (smira) [inline internal/pkg/provision/providers/docker/docker.go:57]: I wonder if we could unify both provisioners now actually?

firecracker passes DNS servers via kernel `ip=` argument, but I think it might just as well use config. DNS shouldn't be needed before config is downloaded.

Comment (rsmitty) [reply internal/pkg/provision/providers/docker/docker.go:57]: Looked like there were some differences in the `WithNetwork` gen option in firecracker. It also needs the eth0 interface unlike docker.

Comment (smira) [reply internal/pkg/provision/providers/docker/docker.go:57]: ah, got it, as it's embedded internally...
