### PR TITLE
test: stabilize race unit-tests (circular, events)

### LINKED ISSUE #2243: flaky unit-test under race: TestEvents_Publish/manymessages_overcap
## Bug Report

unit-test-race failed: https://ci.dev.talos-systems.io/talos-systems/talos/9644/1/24

### Description

Most probably some race which needs to be fixed.

### Logs

```
#172   14.71 === RUN   TestEvents_Publish/manymessages_overcap
#172   14.71 panic: interface conversion: proto.Message is nil, not *machine.SequenceEvent
#172   14.71 
#172   14.71 goroutine 149 [running]:
#172   14.71 github.com/talos-systems/talos/internal/app/machined/pkg/runtime/v1alpha1.TestEvents_Publish.func1.1(0xc0001cc120)
#172   14.71 	/src/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go:83 +0x366
#172   14.71 github.com/talos-systems/talos/internal/app/machined/pkg/runtime/v1alpha1.(*Events).Watch.func1(0xc0003d6070, 0xc000186150, 0xc0001cc120)
#172   14.71 	/src/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go:109 +0x62
#172   14.71 created by github.com/talos-systems/talos/internal/app/machined/pkg/runtime/v1alpha1.(*Events).Watch
#172   14.71 	/src/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go:106 +0xe1
talos-systems/talos#172 14.71 FAIL	github.com/talos-systems/talos/internal/app/machined/pkg/runtime/v1alpha1	0.167s
```

### PR DESCRIPTION
**Pull request by smira**
Fixes #2243

These tests rely on some kind of sync between readers and writers, as if
circular buffer is overrun, test no longer runs as expected.

We use time-sensitive rate limiter to limit write speed to make sure
readers can always catch up. Lowering the rate should slow down writers
and make tests more likely to succeed.

For #2243, the failure was from buffer overrun: when overrun is
detected, `Watch` function closes the channel (and test "receives" zero
element).

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2256)

### CODE REVIEW

File: internal/pkg/circular/circular_test.go [hunk 1]
```diff
@@ -85,7 +85,7 @@ func (suite *CircularSuite) TestStreamingReadWriter() {
 
 		p := data
 
-		r := rate.NewLimiter(500000, 1000)
+		r := rate.NewLimiter(300_000, 1000)
```
Comment (andrewrynhard) [inline internal/pkg/circular/circular_test.go:88]: What does the underscore do?

Comment (smira) [reply internal/pkg/circular/circular_test.go:88]: nothing, just for readability, I looked at constant and couldn't get how many zeros are there, so I added underscore to make it more readable

Comment (andrewrynhard) [reply internal/pkg/circular/circular_test.go:88]: ahh nice, i didn't know go allows that... pretty neat!
