### PR TITLE
fix: bring up bonded interfaces correctly on packet

### LINKED ISSUE #3007: bond creating is not functional on Packet
### Description

From Ubuntu box:

```
  "network": {
    "bonding": {
      "mode": 5,
      "link_aggregation": "bonded",
      "mac": "0c:c4:7a:54:06:4e"
    },
    "interfaces": [
      {
        "name": "eth0",
        "mac": "0c:c4:7a:54:06:4e",
        "bond": "bond0"
      },
      {
        "name": "eth1",
        "mac": "0c:c4:7a:54:06:4f",
        "bond": "bond0"
      }
    ],
    "addresses": [
      {
        "id": "03e490b4-f208-4de1-ab9f-d8d3d564988c",
        "address_family": 4,
        "netmask": "255.255.255.254",
        "created_at": "2019-04-08T21:39:05Z",
        "public": true,
        "cidr": 31,
        "management": true,
        "enabled": true,
        "network": "139.178.69.20",
        "address": "139.178.69.21",
        "gateway": "139.178.69.20",
        "parent_block": {
          "network": "139.178.69.20",
          "netmask": "255.255.255.254",
          "cidr": 31,
          "href": "/ips/415bad3c-b49e-48da-89de-b6efdf448761"
        }
      },
      {
        "id": "3f7853dc-bdec-49bb-bd47-58d650ac8927",
        "address_family": 6,
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:fffe",
        "created_at": "2019-04-08T21:39:04Z",
        "public": true,
        "cidr": 127,
        "management": true,
        "enabled": true,
        "network": "2604:1380:1000:7100::",
        "address": "2604:1380:1000:7100::1",
        "gateway": "2604:1380:1000:7100::",
        "parent_block": {
          "network": "2604:1380:1000:7100:0000:0000:0000:0000",
          "netmask": "ffff:ffff:ffff:ff00:0000:0000:0000:0000",
          "cidr": 56,
          "href": "/ips/fede4caf-cc4e-4d89-8425-82d010ecada5"
        }
      },
      {
        "id": "0d744fff-501e-4347-8fbc-aa128ef250ca",
        "address_family": 4,
        "netmask": "255.255.255.254",
        "created_at": "2019-04-08T21:39:04Z",
        "public": false,
        "cidr": 31,
        "management": true,
        "enabled": true,
        "network": "10.88.101.128",
        "address": "10.88.101.129",
        "gateway": "10.88.101.128",
        "parent_block": {
          "network": "10.88.101.128",
          "netmask": "255.255.255.128",
          "cidr": 25,
          "href": "/ips/84e72255-ea2c-4750-9740-700cd76430ff"
        }
      }
    ]
  },
```

Their setup:

```
auto bond0
iface bond0 inet static
    address 139.178.69.21
    netmask 255.255.255.254
    gateway 139.178.69.20
    bond-downdelay 200
    bond-miimon 100
    bond-mode 5
    bond-updelay 200
    bond-xmit_hash_policy layer3+4
    bond-slaves enp0s20f0 enp0s20f1
    dns-nameservers 147.75.207.207 147.75.207.208
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

### PR DESCRIPTION
**Pull request by smira**
This probably fixes bonding in general if 2nd link in the bond is down.

For packet, set additional options for the bonded interface. In
networkd, add interfaces filtered out by link status as ignored to make
them available as bond subinterfaces.

Fixes #3007 

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]

File: internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go [hunk 1]
```diff
@@ -168,6 +165,10 @@ func (p *Packet) Configuration(ctx context.Context) ([]byte, error) {
 			DeviceCIDR:      fmt.Sprintf("%s/%d", addr.Address, addr.CIDR),
 			DeviceBond: &v1alpha1.Bond{
 				BondMode:       bondMode.String(),
+				BondDownDelay:  200,
+				BondMIIMon:     100,
+				BondUpDelay:    200,
+				BondHashPolicy: "layer3+4",
```
Comment (andrewrynhard) [inline internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go:171]: I don't think this is safe to do across the board. Correct me if I am wrong @Ulexus, but I believe what we put here depends on how Equinix has things setup. And I don't think it is consistent for all machine types.

Comment (smira) [reply internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go:171]: there's nothing for it in Equinix metadata, so I must assume it's the "default" in whatever sense of this word

Comment (andrewrynhard) [reply internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go:171]: Yeah, that was my fear. But I think we need to confirm this. There was something in the packet bonding setup that wasn't consistent. I don't remember what that was.

Comment (Ulexus) [reply internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go:171]: It depends on what that bond mode is.  If it is failover, it needs no coordination.  If it is aggregated, it needs the switch's argeement.

Comment (smira) [reply internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go:171]: @Ulexus it's failover bond only (no link aggregation). 

if you look into #3007 - what I did was more or less copy-paste from what cloud-init does on Ubuntu box. As I understaqnd, hash policy shouldn't apply here, but :man_shrugging: , we can copy from what Packet does via cloud-init

Comment (Ulexus) [reply internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go:171]: Okay, then it should be safe:  no coordination should be needed with Packet... and their thing is hard-coded anyway.  Perhaps they use that when they need to perform switch maintenance?  In any case, we should be safe here.
