### PR TITLE
fix: update the way NTP sync uses `adjtimex` syscall

### LINKED ISSUE #3582: Kernel reports clock to be unsynced
### Description
The general problem is that although Talos is taking care of keeping the system clock in sync with NTP peers, the kernel considers it being unsynced, because of timex status bit `STA_UNSYNC` being set. This bit is cleared by Talos, when time is adjusted using `adjtimex()`, but it seems to get auto-set after 1s. Also, when Talos sets the time using `settime()`, the kernel sets the bit as well.

This affects observability of the nodes sync status using tools like prometheus-node-exporter (metric `node_timex_sync_status` is consistently 0 in my case).

### Logs
not really applicable, but here is some proof NTP is doing its work:
```
9ka-w-1: 2021/05/06 08:16:02  time.SyncController: synchronized RTC with system clock
9ka-w-1: 2021/05/06 08:26:28  time.SyncController: adjusting time by 36.851404ms via 87.249.121.122, state TIME_OK, status STA_PLL | STA_NANO
9ka-w-1: 2021/05/06 08:32:58  time.SyncController: adjusting time by 22.849319ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 08:42:35  time.SyncController: adjusting time by -69.222376ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 08:52:34  time.SyncController: setting time to 2021-05-06 08:52:35.145987688 +0000 UTC m=+2202.010626531 via 87.249.121.122
9ka-w-1: 2021/05/06 08:52:35  time.SyncController: synchronized RTC with system clock
9ka-w-1: 2021/05/06 08:53:12  time.SyncController: adjusting time by 15.811782ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 09:08:45  time.SyncController: setting time to 2021-05-06 09:08:45.427246984 +0000 UTC m=+3172.039830608 via 87.249.121.122
```

### Environment

- Talos version: v0.10.0
- Kubernetes version: v1.21.0
- Platform: metal/kvm

### PR DESCRIPTION
**Pull request by smira**
Fixes #3582

Time adjustment code was rewritten taking a peek at other time sync
implementations. Looks like `adjtimex` was used incorrectly before which
leads to huge time oscillations and `STA_UNSYNC` being set by the
kernel. Instead of setting time via `settimeofday`, use `adjtimex` as
well to set the time on big jump.

With this change, oscillation is pretty stable around zero, in
microsecond range (polling interval lowered for testing):

```
172.20.0.2: 2021/05/06 18:51:28  time.SyncController: adjusting time (slew) by -11.375µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:51:37  time.SyncController: adjusting time (slew) by 426.276µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:51:50  time.SyncController: adjusting time (slew) by -622.037µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:51:58  time.SyncController: adjusting time (slew) by 59.822µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:52:11  time.SyncController: adjusting time (slew) by 126.855µs via 192.36.143.130, state TIME_OK, status STA_NANO | STA_PLL
172.20.0.2: 2021/05/06 18:52:20  time.SyncController: adjusting time (slew) by 17.334µs via 192.36.143.130, state TIME_OK, status STA_NANO | STA_PLL
172.20.0.2: 2021/05/06 18:52:28  time.SyncController: adjusting time (slew) by -108.787µs via 192.36.143.130, state TIME_OK, status STA_NANO | STA_PLL
172.20.0.2: 2021/05/06 18:52:34  time.SyncController: adjusting time (slew) by -71.687µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:52:40  time.SyncController: adjusting time (slew) by 114.759µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:52:47  time.SyncController: adjusting time (slew) by 46.716µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
```

Also one should pick a time server close to the node to get lower RTT
and dispersion.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by rsmitty — APPROVED** [review]

File: internal/pkg/ntp/ntp.go [hunk 1]
```diff
@@ -268,52 +267,55 @@ func (syncer *Syncer) queryServer(server string) (*ntp.Response, error) {
...
 
-	var buf bytes.Buffer
-
-	fmt.Fprintf(&buf, "adjusting time by %s via %s", offset, server)
-
-	req := syscall.Timex{
-		Modes:  timex.ADJ_OFFSET | timex.ADJ_NANO | timex.ADJ_STATUS,
-		Offset: int64(offset / time.Nanosecond),
-		Status: timex.STA_PLL,
+	switch leapSecond { //nolint: exhaustive
```
Comment (AlekSi) [inline internal/pkg/ntp/ntp.go:314]:
```suggestion
	switch leapSecond { //nolint:exhaustive
```

**Review by AlekSi — APPROVED** [review]

File: internal/pkg/ntp/ntp.go (hunk 1 above)
Comment (smira) [reply internal/pkg/ntp/ntp.go:314]: I always miss that!

**Comment by smira** [comment]
re-pushed fixing the nit from @AlekSi , no other changes
