### PR TITLE
fix: return a unique set of errors on retry failure

### LINKED ISSUE #1496: Improve retry library error message
When the retry function fails due to timeout we only get `"timeout"` in the error message. We need to do better than this. Knowing _why_ the logic in the retry function is failing is super useful.

### PR DESCRIPTION
**Pull request by andrewrynhard**
This makes errors more descriptive in the case that a timeout occurs
when using a retry func. Today the error is simply "timeout", but that
doesn't provide anything useful to the user. It now returns a unique set of
errors that are collected through the duration of the retry.

Closes #1496.

### CODE REVIEW

File: pkg/retry/retry.go [hunk 1]
```diff
@@ -24,6 +26,42 @@ type Ticker interface {
...
+	if e.errs == nil {
+		e.errs = make(map[string]error)
+	}
+
+	if _, ok := e.errs[err.Error()]; !ok {
+		e.errs[err.Error()] = err
+	}
+
+	return e
+}
```
Comment (andrewrynhard) [inline pkg/retry/retry.go]: I wonder if we should use a slice to preserve order.

File: pkg/retry/retry.go [hunk 2]
```diff
@@ -24,6 +26,42 @@ type Ticker interface {
...
+
+func (e *ErrorSet) Error() string {
+	if len(e.errs) == 0 {
+		return ""
+	}
+
+	errString := fmt.Sprintf("%d error(s) occurred:", len(e.errs))
+	for _, err := range e.errs {
+		errString = fmt.Sprintf("%s\n%s", errString, err)
```
Comment (smira) [inline pkg/retry/retry.go]: should be `+=` ?

File: pkg/retry/retry.go [hunk 3]
```diff
@@ -24,6 +26,42 @@ type Ticker interface {
...
+
+	mu sync.Mutex
+}
+
+func (e *ErrorSet) Error() string {
+	if len(e.errs) == 0 {
+		return ""
+	}
+
+	errString := fmt.Sprintf("%d error(s) occurred:", len(e.errs))
```
Comment (smira) [inline pkg/retry/retry.go]: missing `\n` ?

File: pkg/retry/retry.go (hunk 2 above)
Comment (smira) [reply pkg/retry/retry.go]: > should be `+=` ?

please disregard, being blind

File: pkg/retry/retry.go (hunk 3 above)
Comment (smira) [reply pkg/retry/retry.go]: > missing `\n` ?

missed that one as well below

File: pkg/retry/retry.go (hunk 1 above)
Comment (smira) [reply pkg/retry/retry.go]: I'm not sure if order matters after deduplication

Comment (andrewrynhard) [reply pkg/retry/retry.go]: SGTM
