### PR TITLE
fix: append domainname to DHCP-sourced hostname

### LINKED ISSUE #1628: DHCP client should tie in domain name
If we receive a domain name from the dhcp server, we should append it to the hostname received.

### PR DESCRIPTION
**Pull request by Ulexus**
If we receive a domain name from the DHCP server, append it to the
received hostname.

Fixes #1628

Signed-off-by: Seán C McCord <ulexus@gmail.com>

### CODE REVIEW

File: internal/app/networkd/pkg/address/dhcp.go [hunk 1]
```diff
@@ -129,7 +130,14 @@ func (d *DHCP) Resolvers() []net.IP {
 func (d *DHCP) Hostname() string {
 	// Truncate the returned hostname to only return
 	// the actual host entry
-	return strings.Split(d.Ack.HostName(), ".")[0]
+	hostname := strings.Split(d.Ack.HostName(), ".")[0]
```
Comment (bradbeam) [inline internal/app/networkd/pkg/address/dhcp.go]: since we do this split later, should we return d.ack.hostname in full if d.ack.domainname == ""?

Comment (Ulexus) [reply internal/app/networkd/pkg/address/dhcp.go]: Good question.  That sounds reasonable.
