### PR TITLE
fix: prevent panic on nil pointer in ServiceInfo method

### LINKED ISSUE #2138: Test panic
### Description

https://ci.dev.talos-systems.io/talos-systems/talos/9137/1/29

### Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93cd0c]
goroutine 557 [running]:
github.com/talos-systems/talos/pkg/client.(*Client).ServiceInfo(0xc000a00b90, 0x1a703e0, 0xc0010c26f0, 0x1813fca, 0x8, 0x0, 0x0, 0x0, 0xc000bc6c60, 0x40c0dc, ...)
	/src/pkg/client/client.go:599 +0x10c
github.com/talos-systems/talos/internal/pkg/cluster/check.ServiceStateAssertion(0x1a703a0, 0xc001387380, 0x1a77120, 0xc0001de460, 0x1813fca, 0x8, 0xc0014efa80, 0x2, 0x2, 0x26428e0, ...)
	/src/internal/pkg/cluster/check/service.go:34 +0x179
github.com/talos-systems/talos/internal/pkg/cluster/check.DefaultClusterChecks.func2.1(0x1a703a0, 0xc001387380, 0x12a05f200, 0x1a703a0)
	/src/internal/pkg/cluster/check/default.go:27 +0xc8
github.com/talos-systems/talos/internal/pkg/conditions.(*pollingCondition).Wait.func1(0x1a703a0, 0xc000acd6e0, 0xc00101f6d0, 0x0, 0x0)
	/src/internal/pkg/conditions/poll.go:55 +0x93
github.com/talos-systems/talos/internal/pkg/conditions.(*pollingCondition).Wait(0xc00101f6d0, 0x1a703a0, 0xc000acd6e0, 0x0, 0x0)
	/src/internal/pkg/conditions/poll.go:63 +0x10d
github.com/talos-systems/talos/internal/pkg/cluster/check.Wait.func1(0xc001387200, 0x1a703a0, 0xc000acd6e0, 0x1a3f660, 0xc00101f6d0)
	/src/internal/pkg/cluster/check/check.go:52 +0x45
created by github.com/talos-systems/talos/internal/pkg/cluster/check.Wait
	/src/internal/pkg/cluster/check/check.go:51 +0x127
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

### PR DESCRIPTION
**Pull request by smira**
Fixes #2138

`FilterMessages` might return `nil` resp if it extracts errors into
`err` from `resp`.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2144)

### CODE REVIEW

File: pkg/client/client.go [hunk 1]
```diff
@@ -592,13 +592,19 @@ func (c *Client) ServiceInfo(ctx context.Context, id string, callOptions ...grpc
 	)
 
 	if err != nil {
-		return
+		return services, err
```
Comment (smira) [inline pkg/client/client.go:595]: this is not me, linter wanted me to do that ;)
