### PR TITLE
fix: bind etcd to IPv6 if available

### LINKED ISSUE #1842: etcd does not bind to IPv6 interface
etcd does not appear to be binding to the IPv6 address(es) of the node, listening only on IPv4.  This will be a problem for IPv6-only installations.

### LINKED ISSUE #1843: etcd PKI certs do not make SAN for full hostname
etcd certs are only valid for the short hostname, not the FQDN.

### PR DESCRIPTION
**Pull request by Ulexus**
If an IPv6 address is available, etcd should bind to `[::]` instead of
`0.0.0.0`.  This will cause etcd to listen on both IPv4 and IPv6
interfaces.

Additionally, this fixes the SAN list for the etcd certificate
generation to include the FQDN of the host.

Fixes #1842
Fixes #1843

Signed-off-by: Seán C McCord <ulexus@gmail.com>

### CODE REVIEW

File: internal/app/machined/pkg/system/services/etcd.go [hunk 1]
```diff
@@ -164,15 +164,24 @@ func generatePKI(config runtime.Configurator) (err error) {
...
 	hostname, err := os.Hostname()
 	if err != nil {
 		return fmt.Errorf("failed to get hostname: %w", err)
 	}
 
+	dnsNames, err := net.DNSNames()
+	if err != nil {
+		return fmt.Errorf("failed to get host DNS names: %w", err)
+	}
+	dnsNames = append(dnsNames, "localhost")
```
Comment (andrewrynhard) [inline internal/app/machined/pkg/system/services/etcd.go]: Looks like linter is mad about this and want a space above this line.

Comment (Ulexus) [reply internal/app/machined/pkg/system/services/etcd.go]: Yeah, just fixed.

**Comment by Ulexus** [comment]
re: testing, yes, definitely... but IPv6 overall in Talos doesn't really work yet.  I'm gradually working through it, though, and most of the problems are on the kubernetes side.

**Comment by Ulexus** [comment]
testing etcd itself on IPv6 should be fine, though
