### PR TITLE
fix: allow node names

### LINKED ISSUE #2163: talosctl nodes no longer accepts names
## Bug Report

As of 67b31029a7838045cb819766a1a53e63addd776c, names are no longer allowed for nodes.  This change was done to _allow_ IPv6 addresses, but in the process blocked names.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

### PR DESCRIPTION
**Pull request by Ulexus**
This allows node names for APID, but checks for empty or port-appended
addresses in a best-effort manner.

Fixes #2163

Signed-off-by: Seán C McCord <ulexus@gmail.com>

# Pull Request

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2164)

### CODE REVIEW

**Comment by Ulexus** [comment]
Working on a better check system...

**Comment by Ulexus** [comment]
Okay, much better now.

File: pkg/net/net.go [hunk 1]
```diff
@@ -50,6 +50,36 @@ func FormatAddress(addr string) string {
 	return addr
 }
 
+// AddressContainsPort checks to see if the supplied address contains both an address and a port.
+// This will not catch every possible permutation, but it is a best-effort routine suitable for prechecking human-interactive parameters.
+func AddressContainsPort(addr string) bool {
+	pieces := strings.Split(addr, ":")
```
Comment (smira) [inline pkg/net/net.go:56]: can we simplify it to:

* if `addr` doesn't contain ':', we let it through
* if `addr` contains `:`, but it parses as valid IP, we let it through?

Comment (Ulexus) [reply pkg/net/net.go:56]: For the case we are looking at right now, that would be fine.  I was making the check a bit more elaborate to be useful in the other direction, too:  checking in cases where an address _should_ contain a port.

I'm not really sure; maybe it _is_ overly-elaborate for what it needs to be.

Comment (Ulexus) [reply pkg/net/net.go:56]: Oh, sorry, no.  That still isn't sufficient:  the problem is that we need to be able to accept DNS _names_ as well as IPs.

Comment (Ulexus) [reply pkg/net/net.go:56]: However, we _can_ branch early in the absence of any `:`, which seems like a reasonable simplification.

Comment (smira) [reply pkg/net/net.go:56]: yep, sounds like I thought about `AddressDoesntContainPort` which might be simpler
