### PR TITLE
fix: talosctl health should not check kube-proxy when it is disabled

### LINKED ISSUE #3299: talosctl health should not check kube-proxy when it is disabled
### Description

Running `talosctl health` when `.cluster.proxy.disabled` is `true` hangs checking for kube-proxy.

### Logs

```
❯ talosctl --context tte-metal -n 10.87.64.11 health
discovered nodes: control plane: ["10.87.64.11"], worker: []
waiting for etcd to be healthy: ...
waiting for etcd to be healthy: OK
waiting for bootkube to finish: ...
waiting for bootkube to finish: OK
waiting for apid to be ready: ...
waiting for apid to be ready: OK
waiting for kubelet to be healthy: ...
waiting for kubelet to be healthy: OK
waiting for all nodes to finish boot sequence: ...
waiting for all nodes to finish boot sequence: OK
waiting for all k8s nodes to report: ...
waiting for all k8s nodes to report: OK
waiting for all k8s nodes to report ready: ...
waiting for all k8s nodes to report ready: OK
waiting for all control plane components to be ready: ...
waiting for all control plane components to be ready: OK
waiting for kube-proxy to report ready: ...
waiting for kube-proxy to report ready: no pods found for namespace "kube-system" and label "k8s-app=kube-proxy"
healthcheck error: rpc error: code = Unknown desc = context deadline exceeded
```

### Environment

- Talos version:
```
Client:
        Tag:         v0.9.0-beta.0
        SHA:         dbcb643e
        Built:
        Go version:  go1.15.8
        OS/Arch:     darwin/amd64

Server:
        NODE:        10.87.64.11
        Tag:         v0.9.0-beta.0
        SHA:         dbcb643e
        Built:
        Go version:  go1.15.8
        OS/Arch:     linux/amd64
```
- Kubernetes version:
```
Client Version: v1.20.4
Server Version: v1.20.4
```
- Platform: `metal`

### PR DESCRIPTION
**Pull request by AlekSi**
Fixes #3299.

- [x] you linked an issue (if applicable)
- [x] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [x] you ran unit-tests (`make unit-tests`)

### CODE REVIEW

**Review by smira — APPROVED** [review]
:+1: :cool:

File: pkg/cluster/check/reporter.go [hunk 1]
```diff
@@ -59,8 +59,11 @@ func (wr *writerReporter) Update(condition conditions.Condition) {
 		coloredLine = color.YellowString("%s", line)
 		wr.lastLineTemporary = true
 		showSpinner = true
-	case strings.HasSuffix(line, "OK"):
-		coloredLine = line
+	case strings.HasSuffix(line, conditions.OK):
+		coloredLine = color.GreenString("%s", line)
```
Comment (AlekSi) [inline pkg/cluster/check/reporter.go:63]: That looks better to me, WDYT?

File: pkg/cluster/check/reporter.go [hunk 2]
```diff
@@ -59,8 +59,11 @@ func (wr *writerReporter) Update(condition conditions.Condition) {
...
+		wr.lastLineTemporary = false
+	case strings.HasSuffix(line, conditions.ErrSkipAssertion.Error()):
+		coloredLine = color.BlueString("%s", line)
```
Comment (AlekSi) [inline pkg/cluster/check/reporter.go:66]: LGTY?

**Review by AlekSi — COMMENTED** [review]
I wonder if more tests can and should be added

**Comment by smira** [comment]
> I wonder if more tests can and should be added

absolutely if you have any ideas

keep in mind that this is very basic, we also have `--run-e2e` flag which triggers Kubernetes e2e tests which can be configured as thorough as we want

File: pkg/conditions/poll_test.go [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+
+	"github.com/stretchr/testify/assert"
+
+	"github.com/talos-systems/talos/pkg/conditions"
+)
+
+func TestPollingCondition(t *testing.T) {
+	t.Parallel()
+
+	t.Run("OK", func(t *testing.T) {
```
Comment (AlekSi) [inline pkg/conditions/poll_test.go:21]: Also, how do you feel about `testing` sub-tests and `testify/suite`? Do we want to replace the latter with the former? Previously I had a lot of problems with a combination of parallel tests + logging in tests + suites, a moving to sub-tests solved them completely. I'm suspicious about `testify/suite` since then :)

**Comment by AlekSi** [comment]
Ok, will think about more tests tomorrow, maybe will send a PR.

File: pkg/conditions/poll_test.go (hunk 3 above)
Comment (smira) [reply pkg/conditions/poll_test.go:21]: I think I used sub-tests in all kinds of ways, including inside `testify/suite` and launching suite multiple times as sub-tests, and it all worked (so far), but I might not have hit the issue yet.

**Comment by smira** [comment]
> /lgtm

build is still running, I don't remember if it will pick it up if it finishes

**Comment by AlekSi** [comment]
I saw it working yesterday, but will keep an eye 👁️

**Review by smira — APPROVED** [review]
