### PR TITLE
fix: refresh control plane endpoints on worker apids on schedule

### LINKED ISSUE #3068: apid loses connectivity to trustd if master IP changes or master goes down (workers)
## Bug Report

apid on workers discovers master endpoints once on startup, finds first working node and sticks to it for cert issue/renewal

if master goes down or gets replaced, apid can't renew certs anymore, so eventually certs expire and connectivity is lost

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

### PR DESCRIPTION
**Pull request by smira**
This moves endpoint refresh from the context of the service `apid` in
`machined` into `apid` service itself for the workers. `apid` does
initial poll for the endpoints when it boots, but also periodically
polls for new endpoints to make sure it has accurate list of `trustd`
endpoints to talk to, this handles cases when control plane endpoints
change (e.g. rolling replace of control plane nodes with new IPs).

Related to #3069

Fixes #3068

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
The downside of this PR is that apid now has access to kubelet PKI, but it's worker node PKI with limited access to K8s APIs.

File: internal/app/apid/main.go [hunk 1]
```diff
@@ -26,15 +26,19 @@ import (
...
+)
 
 func init() {
 	// Explicitly disable memory profiling to save around 1.4MiB of memory.
 	runtime.MemProfileRate = 0
 
 	log.SetFlags(log.Lshortfile | log.Ldate | log.Lmicroseconds | log.Ltime)
 
-	endpoints = flag.String("endpoints", "", "the IPs of the control plane nodes")
+	endpoints = flag.String("endpoints", "", "the static list of IPs of the control plane nodes")
```
Comment (andrewrynhard) [inline internal/app/apid/main.go:40]: Do you know if we support supplying these manually in the config?

**Review by andrewrynhard — APPROVED** [review]

File: internal/app/apid/main.go (hunk 1 above)
Comment (smira) [reply internal/app/apid/main.go:40]: Nope, we don't, but I thought about it and structured the code so that it's easy to add support for it

Comment (andrewrynhard) [reply internal/app/apid/main.go:40]: Yep, exactly. Ok cool. Thanks.

**Review by smira — COMMENTED** [review]
.
