### PR TITLE
fix: retry Kubernetes API errors on cordon/uncordon/etc.

### LINKED ISSUE #3403: reset sequence fails as the node cordon task fails
## Bug Report

Reset sequence should retry transient API server errors.

### Logs

```
[  659.338682] [talos] reset request received
[  659.339676] [talos] reset sequence: 10 phase(s)
[  659.340918] [talos] phase drain (1/10): 1 tasks(s)
[  659.342390] [talos] task cordonAndDrainNode (1/1): starting
[  669.349761] [talos] task cordonAndDrainNode (1/1): failed
[  669.350963] [talos] task cordonAndDrainNode (1/1): done, 10.008409276s
[  669.352312] [talos] phase drain (1/10): failed
[  669.353239] [talos] reset sequence: failed
[  669.354104] [talos] reset sequence: done: 10.014236249s
[  669.355291] [talos] reset failed: error running phase 1 in reset sequence: task 1/1: failed, failed to cordon node e2e-qemu-master-2: 1 error(s) occurred:
[  669.358131] 	Get "https://172.20.1.50:6443/api/v1/nodes/e2e-qemu-master-2?timeout=30s": net/http: TLS handshake timeout
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 0.10.0-alpha.1
- Kubernetes version: [`kubectl version --short`]
- Platform:

### PR DESCRIPTION
**Pull request by smira**
This extracts function which was used in upgrade/convert flows to retry
transient errors to the main `kubernetes` package, expands it to ignore
timeout errors, and it is now used to retry errors where applicable in
`pkg/kubernetes`.

Fixes #3403

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

File: pkg/kubernetes/errors.go [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+func IsRetryableError(err error) bool {
+	if apierrors.IsTimeout(err) || apierrors.IsServerTimeout(err) || apierrors.IsInternalError(err) {
+		return true
+	}
+
+	if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
+		return true
+	}
+
+	netErr := &net.OpError{}
```
Comment (AlekSi) [inline pkg/kubernetes/errors.go:26]: Do we consistently use that form instead of `var netErr net.OpError`?

I wonder if we could add https://github.com/quasilyte/go-consistent to our pipeline to  enforce that

**Review by AlekSi — APPROVED** [review]

File: pkg/kubernetes/errors.go (hunk 1 above)
Comment (smira) [reply pkg/kubernetes/errors.go:26]: these are different forms, `errors.As` requires pointer to pointer here

Comment (AlekSi) [reply pkg/kubernetes/errors.go:26]: Ok, `netErr := new(net.OpError)` then :)

Comment (smira) [reply pkg/kubernetes/errors.go:26]: but the linter looks interesting :+1:

Comment (smira) [reply pkg/kubernetes/errors.go:26]: I don't have strong preference towards one or another, not sure which one is most frequent
