### PR TITLE
fix: ensure ordering of interfaces when deciding hostname

### LINKED ISSUE #1927: [bug] /etc/hosts / IP address inconsistencies due to unordered map
(as discussed with @andrewrynhard)
since `Interfaces` is an unordered map, it causes unpredictable behaviour when picking the hostname

https://github.com/talos-systems/talos/blob/64b5b32732d4023576321111f1cbe79516404758/internal/app/networkd/pkg/networkd/networkd.go#L282

### PR DESCRIPTION
**Pull request by rsmitty**
## What? (description)
fix: ensure ordering of interfaces when deciding hostname

## Why? (reasoning)
This PR will fix some unexpected behavior where we were using Interfaces
as an unordered map, which led to varying behavior with hostname
determination. We will now go through the list of interfaces
alphabetically by name.

Will close #1927

### CODE REVIEW

File: internal/app/networkd/pkg/networkd/networkd.go [hunk 1]
```diff
@@ -280,9 +280,17 @@ func (n *Networkd) decideHostname() (hostname string, domainname string, address
 	address = net.ParseIP("127.0.1.1")
 	hostname = fmt.Sprintf("%s-%s", "talos", strings.ReplaceAll(address.String(), ".", "-"))
 
+	// Sort interface names alphabetically so we can ensure parsing order
+	interfaceNames := make([]string, len(n.Interfaces))
```
Comment (smira) [inline internal/app/networkd/pkg/networkd/networkd.go:285]: this should be `make([]string, 0, len(n.Interfaces))`, as otherwise it creates list of length N and appends N items

File: internal/app/networkd/pkg/networkd/networkd.go [hunk 2]
```diff
@@ -280,9 +280,17 @@ func (n *Networkd) decideHostname() (hostname string, domainname string, address
...
+	for intName := range n.Interfaces {
+		interfaceNames = append(interfaceNames, intName)
+	}
+
```
Comment (smira) [inline internal/app/networkd/pkg/networkd/networkd.go:289]: I guess `sort.Strings(interfaceNames)` is missing here, as otherwise it's equivalent to the code it was before

Comment (rsmitty) [reply internal/app/networkd/pkg/networkd/networkd.go:289]: yep, thanks. just realized myself. give it a refresh.

File: internal/app/networkd/pkg/networkd/networkd.go (hunk 1 above)
Comment (rsmitty) [reply internal/app/networkd/pkg/networkd/networkd.go:285]: ah yep. fixed in amended commit. thx.
